config/routes.rb
Rails.application.routes.draw do
  apipie
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  #resources :items, defaults: {format: :json}

  resources :expenses, defaults: {format: :json}
  
  # You can have the root of your site routed with "root"
  root 'expenses#index'
  
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  #protect_from_forgery with: :exception
  
  protect_from_forgery with: :null_session

  def permission_denied
    render file: "public/401.html", layout: false, status: :unauthorized
  end
end

app/controllers/base_controller.rb
class Api::BaseController < ApplicationController
  before_filter :authenticate_user!

  private

  def permission_denied
    render json: {error: 'unauthorized'}, status: :unauthorized
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!
  before_action :check_owner

  respond_to :html, :json
  
  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = Expense.all
    respond_with @expenses
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
    respond_with @expense
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # POST /expenses
  # POST /expenses.json
  #api :POST, '/expenses.json'
  #param :description, :comment, :amount, :datetime
  def create
    @expense = Expense.create(expense_params)
    @expense.user_id = current_user.id
    @expense.save!
    respond_with @expense, status: 201
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_with Expense.update(params[:id], expense_params), status: 204
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    respond_with @expense.destroy, status: 204
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      puts params.inspect
      @expense = Expense.find(params[:id])
    end

    def expense
      @expense ||= Expense.find_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:description, :comment, :amount, :datetime)
    end
    
    def check_owner
      permission_denied if !expense.nil? && current_user != expense.user
    end
    
    def permission_denied
      render json: {error: 'unauthorized'}, status: :unauthorized
    end
end

app/controllers/sessions_controller.rb
class Api::SessionsController < Devise::SessionsController
  before_action :warden_authenticate

  def create
    sign_in(resource_name, resource)
    resource.reset_authentication_token!
    render json: {auth_token: resource.authentication_token}
  end

  def destroy
    sign_out(resource_name)
    resource.clear_authentication_token!
    render nothing: true
  end

  private

  def warden_authenticate
    self.resource = warden.authenticate!(auth_options)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_form.html.erb
  <form ng-submit= "addExpense()">
    <fieldset>

      <div class="control-group">
        <label class="control-label">
          Description
        </label>
        <div class = "row">
        <div class="controls col-sm-6">
            <input type="text"
                   name="expense[description]"
                   data-ng-model ="expense.description"
                   class="text_area form-control"
                   required>
            <span ng-show="newExpense.description.$error.required"
                class="help-inline">
            Required
          </span>
        </div>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label">
          Comment
        </label>
        <div class = "row">
        <div class="controls col-sm-6">
            <input type="text"
                   name="expense[comment]"
                   ng-model="expense.comment"
                   class="text_area form-control"
                   required>
            <span ng-show="newExpense.comment.$error.required"
                class="help-inline">
            Required
          </span>
        </div>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label">
          Amount
        </label>
        <div class = "row">
        <div class="controls col-sm-6">
            <input type="text"
                   name="expense[amount]"
                   ng-model="expense.amount"
                   class="text_field form-control"
                   required>
            <span ng-show="newExpense.amount.$error.required"
                class="help-inline">
            Required
          </span>
        </div>
        </div>
      </div>

      <div class="control-group">
        <label class="control-label">
          Datetime
        </label>
        <div class='controls'>
          <div class="row">
            <div class= "col-sm-6">
              <div class="form-group">
                  <div class='input-group date' id='datetimepicker1'>
                    <input type='text' 
                            name="expense[datetime]" 
                            ng-model="expense.datetime"
                            id = "expenseDatetime" 
                            class="form-control"
                            required/>
                    <span class="input-group-addon">
                      <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                  </div>
                  <span ng-show="newExpense.datetime.$error.required"
                      class="help-inline">
                  Required
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>

      <br/>
      <div class="form-actions">
        <input type="submit" value="Add" class="btn btn-primary">
       <button type="button" id="cancleAddExpense" class="btn">Cancel</button>
      </div>
    </fieldset>
  </form>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render 'form' %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<div class="container" ng-view>
</div>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Term:</strong>
  <%= @expense.term %>
</p>

<p>
  <strong>Value:</strong>
  <%= @expense.value %>
</p>

<p>
  <strong>Datetime:</strong>
  <%= @expense.datetime %>
</p>

<p>
  <strong>User:</strong>
  <%= @expense.user %>
</p>

<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="Expenses">
<head>
  <title>ExpensesTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="user_nav" class="container">
		<% if user_signed_in? %>
		  Logged in as <strong><%= current_user.email %></strong>.
		  <%= link_to 'Edit profile', edit_user_registration_path %> |
		  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
		<% else %>
		  <%= link_to "Sign up", new_user_registration_path %> |
		  <%= link_to "Login", new_user_session_path %>
		<% end %>
	</div>

	<% flash.each do |name, msg| %>
		<%= content_tag :div, msg, id: "flash_#{name}" %>
	<% end %>
	<div class= "container">
		<%= yield %>
	</div>

</body>
</html>